Simonas/funcionallity
DziugasRam/Local-Stars pull request #67
Opened 2020-12-10 12:00 UTC by simonasve

2020-12-10 12:45 UTC, DziugasRam requested changes

2020-12-10 12:45 UTC, DziugasRam commented on Frontend/local-stars/src/Components/ProductCard.tsx
> +        const isLiked = props.isLiked;
galima tiesiog 
return props.isLiked ? <FavoriteIcon /> : <FavoriteBorderIcon />
ir gerai visai nenestinti komponentu vieno kitame

2020-12-10 12:45 UTC, DziugasRam commented on Frontend/local-stars/src/Components/ProductCard.tsx
> +        if (isLiked === true) {
setIsLiked(!isLiked)

2020-12-10 12:45 UTC, DziugasRam commented on Frontend/local-stars/src/pages/Buyer.tsx
> +  const getPhoneNumber = (seller: {phoneNumber: string;}) => seller.phoneNumber
yra kazkokia priezastis prideti sitas funkcijas, jeigu tiesiog galima iskarto accesinti property?

2020-12-10 12:45 UTC, DziugasRam commented on .gitignore
> +/Frontend/local-stars/src/configuration.ts
kazkaip nepaignorino, nes yra tarp failu configuration.ts

2020-12-11 12:27 UTC, GintareLi approved these changes

2020-12-11 12:28 UTC, GintareLi approved these changes

2020-12-11 12:28 UTC, GintareLi approved these changes

2020-12-11 12:30 UTC, GintareLi approved these changes

2020-12-11 12:30 UTC, DziugasRam approved these changes

2020-12-11 12:40 UTC, merged